### PR TITLE
Add test for nim.

### PR DESCRIPTION
**Pull request by treeform**

### CODE REVIEW

**Comment by iffy** [comment]
You beat me to it :)

I saw it get to 1989 deep.  Is that what you saw?

**Comment by treeform** [comment]
I saw `1993` deep on Mac OS X.

**Comment by iffy** [comment]
Ooo, compiling with `-d:release` gets to `100000` deep (also on macOS)

**Comment by lovasoa** [comment]
Great! can you add the results to the README? And maybe the add nim to the .travis ?

**Comment by treeform** [comment]
You right! It probably causes tail call optimization. 

100000 as well

**Comment by treeform** [comment]
Hmm I don't know how to test travis or how it works.

**Comment by iffy** [comment]
Something like this might work:

```diff
diff --git a/.travis.yml b/.travis.yml
index 64566fc..52274b5 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,3 +6,18 @@ matrix:
 
     - language: ruby
       script: ./test_parser.sh ruby parser_ruby.rb
+
+    # nim
+    - language: c 
+      os: linux
+      compiler: gcc
+      install:
+        - export CHOOSENIM_NO_ANALYTICS=1
+        - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
+        - sh init.sh -y
+        - export PATH=~/.nimble/bin:$PATH
+        - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
+        - choosenim stable
+      script:
+        - nim c -d:release parser_nim.nim
+        - ./test_parser.sh ./parser_nim
```

**Pull request closed without merging**
